package com.entities;

public enum Departamentos {
	ARTIGAS, CANELONES, CERRO_LARGO, COLONIA, DURAZNO, FLORES, FLORIDA, LAVALLEJA,
	MALDONADO, MONTEVIDEO, PAYSANDU, RIO_NEGRO, RIVERA, ROCHA, SALTO, SAN_JOSE,
	SORIANO, TACUAREMBO, TREINTA_TRES

}
